name: MEDs docker

# Controls when the action will run. Triggers the workflow on release 
# event

on:
  push:
    branches: [meds\dev]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  webhook:
    name: Send event
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - name: Repository Dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_TOKEN }}
        repository: VirtoCommerce/vc-meds-docker
        event-type: build-storefront-image