# v1.0.0
name: Release - Quick release

on:
  workflow_dispatch:

jobs:
  release:
    uses: VirtoCommerce/.github/.github/workflows/release.yml@v3.800.2
    secrets:
      envPAT: ${{ secrets.REPO_TOKEN }}
